baseURL = 'https://github.com/fabiomen10/fabiomen10.github.io'
languageCode = 'en-us'
title = "Break2Me Blog"
theme = 'coming-soon'

[params]
    title = "Break2Me Blog" 
    description = "A simple countdown"
    favicon = ""
    message = "COMING SOON!" 
    release = "Jun 30, 2024" 
    background = "" 